language: node_js
dist: trusty
notifications:
  email: false
before_script:
- curl https://keybase.io/travi/key.asc | gpg --import
before_deploy:
- npm run build
- git config --global user.name "$GIT_NAME"
- git config --global user.email "$GIT_EMAIL"
deploy:
- skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
  - secure: qUAs66CyRaI+FNW7uLLYY2BrnDeiQh1yXkz7RriqMm6u+NTgW2ZWcmvZA2YCNBsEfBkV5Vlr6rYb3MBfAn6rzrfNMAmhlYj2L1QUsZeIO3Ur4rr/pkZrgzebFAWKFYeZP+HRYmoZaYW1OwZgCdXvSYrCC9fmSphhCOoaVSAUG/mDqNxTA21WKvaIhebEkli4oHwp+mcZSdgzIPzsirC/H2G5Rwa2psxCukWCsakj2rQ5YBsfB/f8Eu3deUCi0pTPu7NyzLukh7c5B4vl5Ar81UnVNyp0M3C4ZzScETXnMq34AWGKGAR5wA2pLN6DeNIUO1bFeTCc8jvQz3BMfuxpsZwO+BDexOvYel6O9J9y+TSyJofMhuLhOd3+Yu38C5OAyq/Jm35PYyDrzSxOkqSzrI7sbuYx8ewGRBqA1wOe2QOZfwa/ABL2sLlVQkSokRmxIGGNFVCONMzispUggFML6pkuaWCDH/fpSGsN57wkC0Mk2fiyYEo1jy39OdgVU0HiezfF3VxjGw2u5CDpRhEWpu15f61uTmTHTrqNW0Jv4nXzXS8JlTYMZahErW8pGZ6c8uOz05dSHctCgOVI50Y04xCng+9D7qKmP1H6qHblfV6FZu1x6mhwjyVhnXCcfKsKgm5YYqOyQ9nmVA8TZwkQyBp05f/hNXUDQYPmdGO/+yQ=
  - secure: yHzS44Jf5gLVtr5f0S9wN9xXcNGlGx9J/bejdqUVbKVEQPLiQNQjYPsweAVyUnpff95osCH3+G7lfxp/CaxHiQ5pJ6m+fxrajJKfyTll9ZNDkLwznOmTYKgKpRafiW1nDNpf9KAuK961kOg4oZbWJ/f7HNVCHSDKsDfmZ/OW/YEJgEYHMekNOe473DH1f6bLkwYNwjXL23zUvfanr3AL24K8tH8pYTsFGhAmvCgk9jiH5RyYgyiUW7jtbtkZc8bPiFYeFuoK/gKdqTWcWqaHfaEsj3MHkI8RB+bncx1pAnvNBv665zxhIljDnEy0jU3ce7pxA8GWV+2Aa0vW3eh9ZFAu6aCoxpT49WpdUKkTbyCNxKYoJ3mz6X7OQTOCkIq2wQAr1gwARePCowo5c/tMsi3dzvxT5GtULYbxcM45IRPTmUGoTpUsR0THbJ6Nd03Gxqmvs98yfktW2OPFbAGqRp0WQSg8lXJwmLDwYMHLOoss+QTjC5pqyhGMCmZFY662EWSvBRpybZb5bRo8KA/O+PP9Tq1k+HIENsIYALOCgxyyHQT71gstWTfNKU4ZCe/8wTOva8gy6IlGsjR9TLP1+/UcXe7ExckdCLavxSpJ197oN3DuQfoGqA+Vo9OvWKSu/23JWRYxx6vAGQGwpGA6hViSiyLAKfGBGkmw4qZ6HQQ=
