name: Node.js CI
'on':
  push:
    branches:
      - master
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          fetch-depth: 0
      - name: Import Public PGP Key
        run: curl https://keybase.io/travi/key.asc | gpg --import
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm audit signatures
      - run: npm test
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      # - name: report webpack stats
        # run: npm run packtracker:publish
        # env:
          # PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
          # PT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: verify
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: npm audit signatures
      - run: npm run deploy:netlify -- --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
permissions:
  contents: read
