name: Percy Snapshots

on: push

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Read .nvmrc
        run: 'echo ::set-output name=NVMRC::$(cat .nvmrc)'
        id: nvm
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - uses: bahmutov/npm-install@237ded403e6012a48281f4572eab0c8eafe55b3f # v1.10.1
      - name: Percy Snapshots
        run: npm run snapshot
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
